/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package demomonitor;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class demo_monitorConstants {

  public static final int SLEEP_TIME = 4;

  public static final int TOTAL_SECS_IN_ADAY = 86400;

  public static final Map<METRIC,String> METRIC_STR = new HashMap<METRIC,String>();
  static {
    METRIC_STR.put(demomonitor.METRIC.CPU_SYS, "sys");
    METRIC_STR.put(demomonitor.METRIC.CPU_USR, "usr");
    METRIC_STR.put(demomonitor.METRIC.RAM_PHYSIC, "memory");
    METRIC_STR.put(demomonitor.METRIC.RAM_SWAP, "swap");
    METRIC_STR.put(demomonitor.METRIC.DISK_READ, "read speed");
    METRIC_STR.put(demomonitor.METRIC.DISK_WRITE, "write speed");
    METRIC_STR.put(demomonitor.METRIC.DISK_FREE, "free space");
    METRIC_STR.put(demomonitor.METRIC.NET_IN, "inspeed");
    METRIC_STR.put(demomonitor.METRIC.NET_OUT, "outspeed");
  }

  public static final Map<TAG,String> TAG_STR = new HashMap<TAG,String>();
  static {
    TAG_STR.put(demomonitor.TAG.CPU, "cpu");
    TAG_STR.put(demomonitor.TAG.RAM, "ram");
    TAG_STR.put(demomonitor.TAG.DISK, "disk");
    TAG_STR.put(demomonitor.TAG.NET, "network");
  }

}
