/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package demomonitor;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TAG implements org.apache.thrift.TEnum {
  CPU(0),
  RAM(1),
  DISK(2),
  NET(3);

  private final int value;

  private TAG(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TAG findByValue(int value) { 
    switch (value) {
      case 0:
        return CPU;
      case 1:
        return RAM;
      case 2:
        return DISK;
      case 3:
        return NET;
      default:
        return null;
    }
  }
}
