// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "thrift_gen_code/databaseCenter.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

#include <ctime>
#include <iostream>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace ::demomonitor;
using namespace std;

class databaseCenterHandler : virtual public databaseCenterIf {
public:

    databaseCenterHandler() {
        // Your initialization goes here
    }
    // recieved data from clientS

    void send_data_to_server (const dataCollector& dat) {
        // Your implementation goes here
        time_t _time = time(0); // get time now
        struct tm * _tnow = localtime(&_time);
        cout << _tnow->tm_hour << ":" << _tnow->tm_min << ":" << _tnow->tm_sec << " " << dat << "send_data\n";

    }
    // check range and send data to client

    void recieve_data_from_server(std::vector<double> & _return, const std::string& begintime, const std::string& endTime) {
        // Your implementation goes here
        time_t _time = time(0); // get time now
        struct tm * _tnow = localtime(&_time);
        cout << _tnow->tm_hour << ":" << _tnow->tm_min << ":" << _tnow->tm_sec << " " << begintime << "recieve_data " << endTime << "\n";
    }


};

int main(int argc, char **argv) {
    cout << "running.." << endl;
    int port = 9090;
    shared_ptr<databaseCenterHandler> handler(new databaseCenterHandler());
    shared_ptr<TProcessor> processor(new databaseCenterProcessor(handler));
    shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
    shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
    shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

    TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
    server.serve();
    return 0;
}

